# Generated by Django 2.2.6 on 2019-10-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id',
                 models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                  verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('rating', models.FloatField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('last_match_time', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=50)),
                ('logo_url', models.URLField(max_length=500)),
            ],
        ),
    ]
