# Generated by Django 2.2.6 on 2019-10-29 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='competive_rank',
            new_name='competitive_rank',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='solo_competive_rank',
            new_name='solo_competitive_rank',
        ),
        migrations.AlterField(
            model_name='player',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
        ),
    ]
