# Generated by Django 2.2.6 on 2019-10-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191029_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='competitive_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='leaderboard_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='loccountrycode',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='rank_tier',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='solo_competitive_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='steamid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
